version: "3.9"

services:
  fastfood-db:
    image: mysql:8.0
    container_name: fastfood-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: fiap-fastfood
      MYSQL_ROOT_PASSWORD: rootfiap
      MYSQL_USER: fiap_postech
      MYSQL_PASSWORD: fiap
    command: ["mysqld", "--log-bin=OFF"]
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

    # ðŸ”¥ Healthcheck para garantir que o MySQL sÃ³ fica "pronto" quando estÃ¡ aceitando conexÃµes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootfiap"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  fiap-fastfood-produtos:
    image: maycondockeraccount/fiap-fastfood-produtos:latest
    container_name: fiap-fastfood-produtos

    # ðŸ”¥ SÃ³ sobe depois que o MySQL estiver HEALTHY
    depends_on:
      fastfood-db:
        condition: service_healthy

    environment:
      DATASOURCE_URL: jdbc:mysql://fastfood-db:3306/fiap-fastfood
      DATASOURCE_USERNAME: fiap_postech
      DATASOURCE_PASSWORD: fiap

    ports:
      - "8080:8080"
