apiVersion: v1
kind: ConfigMap
metadata:
  name: app-produtos-config
data:
  DATASOURCE_URL: "jdbc:mysql://fiap-fastfood-aurora-instance-1.cvepqcjgr17y.us-east-1.rds.amazonaws.com:3306/fiapfastfood" #"jdbc:mariadb://fastfood-db-service:3306/fiap-fastfood"
  MARIADB_DATABASE: "fiapfastfood"