apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-produtos-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-produtos-java
  template:
    metadata:
      labels:
        app: app-produtos-java
    spec:
      containers:
        - name: app-produtos-java
          image: REPO_ECR #maycondockeraccount/fiap-fastfood-produtos:latest #maycondockeraccount/k8s:latest #maycondockeraccount/fiap-fastfood #alexguimaraes21/fiap-fastfood:latest
          # endpoint da imagem de teste k8s = http://localhost:8080/api/v1/mockApi
          resources:
            requests:
              cpu: "100m" # Solicita 0.1 de um core de CPU
              memory: "128Mi" # Solicita 128 megabytes de memória
            limits:
              cpu: "500m" # Limite de 0.5 de um core de CPU
              memory: "256Mi" # Limite de 256 megabytes de memória
          ports:
            - containerPort: 8080
#            - name: TZ
#              valueFrom:
#                secretKeyRef:
#                  name: app-secret
#                  key: TZ
#
          env:
#            - name: TZ
#              valueFrom:
#                secretKeyRef:
#                  name: app-secret
#                  key: TZ
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-produtos-config
                  key: DATASOURCE_URL

            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-produtos-secret
                  key: DATASOURCE_USERNAME

            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-produtos-secret
                  key: DATASOURCE_PASSWORD

            - name: DATASOURCE_POOL-NAME
              valueFrom:
                secretKeyRef:
                  name: app-produtos-secret
                  key: DATASOURCE_POOL-NAME

            - name: DATASOURCE_MAXIMUM-POOL-SIZE
              valueFrom:
                secretKeyRef:
                  name: app-produtos-secret
                  key: DATASOURCE_MAXIMUM-POOL-SIZE