apiVersion: v1
kind: Service
metadata:
  name: app-produtos-service
spec:
  selector:
    app: app-produtos-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer