apiVersion: v1
kind: Secret
metadata:
  name: app-produtos-secret
type: Opaque
data:
  DATASOURCE_URL: ZmlhcC1mYXN0Zm9vZC1hdXJvcmEtaW5zdGFuY2UtMS5jdmVwcWNqZ3IxN3kudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tCg== #fiap-fastfood-aurora-instance-1.cvepqcjgr17y.us-east-1.rds.amazonaws.com:3306/fiapfastfood
  DATASOURCE_USERNAME: YWRtaW4= #admin
  DATASOURCE_PASSWORD: YWRtaW4xMjM= #admin123
  DATASOURCE_POOL-NAME: ZmlhcGZhc3Rmb29k #fiapfastfood #ZmlhcGZhc2Zvb2Q= #fiapfasfood
  DATASOURCE_MAXIMUM-POOL-SIZE: MTA= #10
