name: SonarCloud Scan (Maven, Java 21)

on:
  push:
    branches: ["main", "master", "feature/msProdutos"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  YOUR_PROJECT_KEY: thiagolinoz_FastFoodProdutos
  YOUR_SONARCLOUD_ORGANIZATION: thiagolinoz
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21 and cache Maven deps
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run unit tests
        run: mvn -B test
        
  sonar:
    name: SonarCloud analysis
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21 and cache Maven deps
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run Sonar analysis
        run: |
          mvn -B -DskipTests=true verify sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ env.SONAR_TOKEN }} \
            -Dsonar.projectKey=${{ env.YOUR_PROJECT_KEY }} \
            -Dsonar.organization=${{ env.YOUR_SONARCLOUD_ORGANIZATION }}
